# Generated by Django 3.0.2 on 2020-04-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='truckid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='order',
            name='whid',
            field=models.IntegerField(default=-1),
        ),
    ]
