# Generated by Django 2.2.10 on 2020-04-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200421_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=-1, verbose_name='Product Count'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pid',
            field=models.IntegerField(default=-1, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='x',
            field=models.IntegerField(default=-1, verbose_name='Destination X Value'),
        ),
        migrations.AlterField(
            model_name='order',
            name='y',
            field=models.IntegerField(default=-1, verbose_name='Destination Y Value'),
        ),
    ]
