# Generated by Django 3.0.2 on 2020-04-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200422_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='arrived',
        ),
        migrations.RemoveField(
            model_name='order',
            name='loaded',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ready',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='whid',
            field=models.IntegerField(default=0),
        ),
    ]
