# Generated by Django 2.2.12 on 2020-04-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200423_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pid',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=-1, verbose_name='Product'),
        ),
    ]
