# Generated by Django 2.2.12 on 2020-04-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200424_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pid',
            field=models.IntegerField(default=-1, verbose_name='Product ID'),
        ),
    ]
