# Generated by Django 3.0.5 on 2020-04-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200424_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='xxx@qq.com', max_length=254),
        ),
    ]
