version: '2'

services:
  web:
      build: ./web-app
      user: nobody
      command: /code/runserver.sh
      volumes:
        - ./web-app:/code
      expose:
        - "8000"
        - "33333"
        - "12345"
        - "23456"
      ports:
        - "33333:33333"
        - "12345:12345"
        - "23456:23456"
volumes:
   data-volume: 